data_dir: ""

affordance:
  ["openable", "cuttable", "pourable", "containable", "supportable", "holdable"]
num_objects: 12

crf:
  weight: 0.1
  kernels_radius: 5
  kernels_desc:
    -
      weight: 1
      xy: 20
      image: 0.1

dataset_mean: [132.2723, 106.8666, 112.8962]
dataset_std: [68.9081, 71.0827, 72.8808]

epochs: 100
batch_size: 4
workers: 10

lr: 0.001
momentum: 0.9
weight_decay: 0.0001

save_dir: ""

resume: ""
restart: false
